version: "3"

services:
  react-docker:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - ./src:/app/src:ro
    environment:
      - REACT_APP_NAME=Mizael
    
    